### ISSUE TITLE
[Meta] Todo list

### ISSUE THREAD

**Issue by snide** [Siege-Perilous/tableslayer#69]
- Email
  - [x] Transactional emails work
  - [x] Marketing emails work
- Files / CDN
  - [x] Cloudflare R2 set up as CDN
  - [x] Image transformations work
- Users
  - [x] Users can signup
  - [x] Users can login
  - [x] Users can reset password
  - [x] Users can validate email
  - [x] Gravitar support
  - [ ] Users can destroy account
  - [x] Profile page is styled https://github.com/Siege-Perilous/tableslayer/pull/171
- UI chrome / head
  - [x] Nav / header system
  - [x] Page titles / descriptions
  - [x] Open graph
- Sessions
  - [x] Sessions have parent data schema
  - [x] Sessions have individual DB with migrations
  - [x] Auto create session on user signup
  - [x] Admin / editor of party can create new sessions https://github.com/Siege-Perilous/tableslayer/pull/88
  - [x] Admin / editor of party can delete sessions https://github.com/Siege-Perilous/tableslayer/pull/88
  - [x] Admin / editor can rename sessions https://github.com/Siege-Perilous/tableslayer/pull/88
  - [x] Sessions can be exported https://github.com/Siege-Perilous/tableslayer/pull/229
  - [x] Sessions can be imported https://github.com/Siege-Perilous/tableslayer/pull/229
- Scenes
  - [x] Scenes can be be created 
  - [x] Scenes can be renamed https://github.com/Siege-Perilous/tableslayer/pull/156
  - [x] Scenes can be deleted
  - [x] Scenes can be copied https://github.com/Siege-Perilous/tableslayer/pull/203
  - [x] Scenes can be reordered https://github.com/Siege-Perilous/tableslayer/pull/190
  - [x] Scene state is tied to Stage https://github.com/Siege-Perilous/tableslayer/pull/112
  - [x] Scene state is saved to Session DB
  - [x] Scene has player view https://github.com/Siege-Perilous/tableslayer/pull/112
  - [x] Player view is synced with Admin edits https://github.com/Siege-Perilous/tableslayer/pull/112
  - [x] ~Store assets as blob in DB~ Decided against this
  - AI maps
    - [ ] Automate map creation through Midjourney prompting
    - [ ] Tie to voice prompt
- Party
  - [x] Can invite another user to party
  - [x] User can accept / deny invite with email 
  - [x] Admin can change role of other invited users https://github.com/Siege-Perilous/tableslayer/pull/70
  - [x] Admin can cancel invite https://github.com/Siege-Perilous/tableslayer/pull/70
  - [x] User can create a new party post signup https://github.com/Siege-Perilous/tableslayer/pull/72
  - [x] User can leave a party https://github.com/Siege-Perilous/tableslayer/pull/70
  - [x] Admin can remove a user from party https://github.com/Siege-Perilous/tableslayer/pull/70
  - [x] Party can be renamed https://github.com/Siege-Perilous/tableslayer/pull/72
  - [x] Party can be deleted https://github.com/Siege-Perilous/tableslayer/pull/72
  - [x] Make sure user can't leave party if they are the only admin
- Billing
  - [x] Set up upgrade flow with LS https://github.com/Siege-Perilous/tableslayer/pull/158
  - [ ] Make sure you can't delete a party if it has an active subscription
  - [x] Limit functionality based on plans https://github.com/Siege-Perilous/tableslayer/pull/194
- Scheduling events
  - [ ] Create new event
  - [ ] Email event request
  - [ ] Email drip reminders for event
  - [ ] Interface to propose times
  - [ ] Email summary once agreed
  - [ ] Delete event 
- Devops
  - [x] Set up sentry
  - [x] CI for linting / TS
  - [x] Previews
  - [ ] Enable remote caching for turbo
  - [x] Create staging DB on PRs https://github.com/Siege-Perilous/tableslayer/pull/76
  - [x] Run migrations on preview DBs in PRs https://github.com/Siege-Perilous/tableslayer/pull/162
  - [x] Run migrations against prod on merges https://github.com/Siege-Perilous/tableslayer/pull/162
- Marketing
  - [ ] Create Table Slayer landing page
  - [x] Create various social accounts
  - [ ] Create Siege Perilous landing page
  - [x] Basic SEO
- Playwright tests
  - [x] Test login flow
  - [x] Test form validation
  - [ ] Test reset password flow
  - [x] Test signup flow (likely require staging DBs)
  - [ ] Test party invite flow
  - [ ] Test session creation flow
  - [ ] Test scene creation flow
